pipeline {
    agent any
    tools {
        jdk 'jdk17'
        nodejs 'node16'
    }
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }
    stages {
        stage('Clean Workspace') {
            steps { cleanWs() }
        }
        stage('Checkout from Git') {
            steps { checkout scm }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh "${SCANNER_HOME}/bin/sonar-scanner -Dsonar.projectKey=Netflix -Dsonar.projectName=Netflix"
                }
            }
        }
        stage('Quality Gate') {
            steps { waitForQualityGate abortPipeline: true }
        }
        stage('Install Dependencies') {
            steps { sh "npm install" }
        }
        stage('Trivy File Scan') {
            steps { sh "trivy fs . > trivy-fs-report.txt" }
        }
        stage('Docker Build & Push') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker', url: 'https://index.docker.io/v1/') {
                        sh "docker build -t netflix-clone ."
                        sh "docker tag netflix-clone your-docker-id/netflix-clone:latest"
                        sh "docker push your-docker-id/netflix-clone:latest"
                    }
                }
            }
        }
        stage('Trivy Image Scan') {
            steps { sh "trivy image your-docker-id/netflix-clone:latest > trivy-image-report.txt" }
        }
        stage('Deploy to Kubernetes') {
            steps { sh "kubectl apply -f kubernetes/deployment.yaml" }
        }
    }
}
